name: gg_check
description: Offers pre-commit checks like analyzing, linting, tests and coverage.
version: 1.0.0
repository: https://github.com/inlavigo/gg_check.git

environment:
  sdk: ">=3.3.0<4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  colorize: ^3.0.0
  dart_ping: ^9.0.1
  path: ^1.8.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  pana: ^0.22.1
  test: ^1.24.0
