name: gg_check
description: Offers pre-commit checks like analyzing, linting, tests and coverage.
version: 1.0.0
repository: https://github.com/inlavigo/gg_check

environment:
  sdk: ^3.4.0-120.0.dev

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.7.2
  dart_ping: ^9.0.1
  lints: ^3.0.0
  pana: ^0.22.1
  recase: ^4.1.0
  test: ^1.24.0
  yaml: ^3.1.2
