name: gg
description: A collection of checks and actions like analyzing, linting, testing, code coverage, committing, pushing, publishing.
version: 1.0.0
repository: https://github.com/inlavigo/gg.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^1.0.3
  gg_console_colors: ^2.0.1
  gg_git: ^1.0.0
  gg_log: ^1.0.0
  gg_process: ^1.0.6
  gg_publish: ^1.0.1
  gg_version: ^1.0.0
  mocktail: ^1.0.3
  path: ^1.8.0
  recase: ^4.1.0

dev_dependencies:
  fake_async: ^1.3.1
  gg_capture_print: ^1.0.3
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0
