name: gg
description: A collection of checks and actions like analyzing, linting, testing, code coverage, committing, pushing, publishing.
version: 3.0.12
repository: https://github.com/inlavigo/gg.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_args: ^2.0.2
  gg_console_colors: ^2.0.1
  gg_git: ^2.5.15
  gg_is_flutter: ^1.0.6
  gg_json: ^1.0.0
  gg_log: ^1.0.0
  gg_process: ^1.0.6
  gg_publish: ^3.0.13
  gg_status_printer: ^1.1.0
  gg_test: ^1.1.1
  gg_version: ^4.0.2
  meta: ^1.12.0
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4
  recase: ^4.1.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0
  gg_capture_print: ^1.0.3
  gg_changelog: ^1.0.11
  gg_is_github: ^1.0.4
  matcher: ^0.12.16+1

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^4.0.0
  test: ^1.24.0

executables:
  gg:
#change
